export const type = {
  USER_SIGNUP_REQUESTED: "USER_SIGNUP_REQUESTED",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",

  USER_SIGNIN_REQUESTED: "USER_SIGNIN_REQUESTED",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILED: "USER_SIGNIN_FAILED",

  USER_REQUESTED: "USER_REQUESTED",
  USER_SUCCESS: "USER_SUCCESS",
  USER_FAILED: "USER_FAILED",

  USER_INFO_REQUESTED: "USER_INFO_REQUESTED",
  USER_INFO_SUCCESS: "USER_INFO_SUCCESS",
  USER_INFO_FAILED: "USER_INFO_FAILED",

  JOBS_LIST_REQUESTED: "JOBS_LIST_REQUESTED",
  JOBS_LIST_SUCCESS: "JOBS_LIST_SUCCESS",
  JOBS_LIST_FAILED: "JOBS_LIST_FAILED",

  POST_JOB_REQUESTED: "POST_JOB_REQUESTED",
  POST_JOB_SUCCESS: "POST_JOB_SUCCESS",
  POST_JOB_FAILED: "POST_JOB_FAILED",

  JOBS_LIST_BY_ID_REQUESTED: "JOBS_LIST_BY_ID_REQUESTED",
  JOBS_LIST_BY_ID_SUCCESS: "JOBS_LIST_BY_ID_SUCCESS",
  JOBS_LIST_BY_ID_FAILED: "JOBS_LIST_BY_ID_FAILED",

  APPLICATIONS_LIST_REQUESTED: "APPLICATIONS_LIST_REQUESTED",
  APPLICATIONS_LIST_SUCCESS: "APPLICATIONS_LIST_SUCCESS",
  APPLICATIONS_LIST_FAILED: "APPLICATIONS_LIST_FAILED",

  CURRENT_USER_REQUESTED: "CURRENT_USER_REQUESTED",
  CURRENT_USER_SUCCESS: "CURRENT_USER_SUCCESS",
  CURRENT_USER_FAILED: "CURRENT_USER_FAILED",

  POST_APPLICATION_REQUESTED: "POST_APPLICATION_REQUESTED",
  POST_APPLICATION_SUCCESS: "POST_APPLICATION_SUCCESS",
  POST_APPLICATION_FAILED: "POST_APPLICATION_FAILED",

  RECRUITER_APPLICATIONS_LIST_REQUESTED:
    "RECRUITER_APPLICATIONS_LIST_REQUESTED",
};
