export const type = {
    USER_SIGNUP_REQUESTED: 'USER_SIGNUP_REQUESTED',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',

    USER_SIGNIN_REQUESTED: 'USER_SIGNIN_REQUESTED',
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAILED: 'USER_SIGNIN_FAILED',

    USER_INFO_REQUESTED: 'USER_INFO_REQUESTED',
    USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
    USER_INFO_FAILED: 'USER_INFO_FAILED'
};
