export const type = {
  USER_SIGNUP_REQUESTED: "USER_SIGNUP_REQUESTED",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",

  USER_SIGNIN_REQUESTED: "USER_SIGNIN_REQUESTED",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAILED: "USER_SIGNIN_FAILED",

  USER_REQUESTED: "USER_REQUESTED",
  USER_SUCCESS: "USER_SUCCESS",
  USER_FAILED: "USER_FAILED",

  USER_INFO_REQUESTED: "USER_INFO_REQUESTED",
  USER_INFO_SUCCESS: "USER_INFO_SUCCESS",
  USER_INFO_FAILED: "USER_INFO_FAILED",

  JOBS_LIST_REQUESTED: "JOBS_LIST_REQUESTED",
  JOBS_LIST_SUCCESS: "JOBS_LIST_SUCCESS",
  JOBS_LIST_FAILED: "JOBS_LIST_FAILED",

  POST_JOB_REQUESTED: "POST_JOB_REQUESTED",
  POST_JOB_SUCCESS: "POST_JOB_SUCCESS",
  POST_JOB_FAILED: "POST_JOB_FAILED",
};
