import React from 'react';
import companyLogo from '../Images/companyLogo.jpg';
import {Paid, Group, Work, School, Upload, Article} from '@mui/icons-material';
import {Avatar, Button, Divider, Grid, Typography, TextField, Paper, Box,CardContent,
    Card} from '@mui/material';

const data= [
                {icon:<School/>, title: "Work Level", value: "Senior"}, 
                {icon:<Work/>, title: "Min Experience", value: "3 years"}, 
                {icon:<Group/>, title: "Employee Type", value: "Part-Time"}, 
                {icon:<Paid/>, title: "Salary", value: "$300/Month"}
            ]
const desc = "This is the random string generated by typing gibbrish, you don’t want to read this for your own sake... Do you still want to read this random string string, please dont even think about it.";
const aboutYou = "The lines are random and randomly typed the lines are random and randomly typed the lines are random and randomly typed randomly typed the lines are random and randomly typed the lines are random and randomly typed randomly typed the lines are random and randomly typed the lines are random and randomly typed randomly typed the lines are random and randomly typed the lines are random."

const CompanyInfo = () => {
    return (
        <Box  sx={{   
            width: 1, 
            height:"20vh",
            bgcolor: "white",
            borderRadius: 2,
        }}>
    <Paper elevation={0} sx={{borderRadius:2}}>
        <Grid container>
            <Grid item md={12} align="center" sx={{mt:2, mb:1}}>
                <Avatar src={companyLogo}/>
            </Grid>
            <Grid item md={12} align="center" sx={{mt:1, align:"center"}}>
                <Typography style={{fontSize:13}}>
                    ANC Private Ltd. <br/>
                    Home Food Delivery
                </Typography>
            </Grid>
            <Grid item sx={{m:1}}>
                <Button variant="outlined" sx={{borderRadius:4, ml:1}}>
                    Following
                </Button>
            </Grid>
            <Grid item sx={{m:1}}>
                <Button variant="outlined" sx={{borderRadius:4}}>
                    Send Mail
                </Button>
            </Grid>
        </Grid>
    </Paper> 
</Box>

    );
}

const JobInfo = () => {
    return (
<Box  sx={{   
                        width: 1, 
                        height:"66vh",
                        bgcolor: "white",
                        borderRadius: 2,
                        
                    }}>
                <Paper elevation={0} sx={{m:1}}>
                    <Grid item>
                        <Typography style={{fontWeight:550}} sx={{mt:1, p:2, ml:-1}}>
                            Food Delivery boy
                        </Typography>
                    </Grid>
                    <Grid item>
                        <Divider/>
                    </Grid>
                    
                    {/* TODO: use array */}
                    {/*{icon:{SchoolIcon}, title: "Work Level", value: "Senior"} */}
                {data.map(item => (
                    <Grid item container sx={{mt:1, ml:0.2}} spacing={1} >
                        <Grid item md={1.5}>
                            {item.icon}
                        </Grid>
                        <Grid item md={6}>
                            <Typography>
                                {item.title}
                            </Typography>
                        </Grid>
                        <Grid item>
                            <Typography>
                                {item.value}
                            </Typography>
                        </Grid>
                    </Grid>
                ))}
                    <Grid item sx={{mt:2}}>
                        <Divider/>
                    </Grid>

                    <Grid item>
                        <Typography style={{fontWeight:550}} sx={{mt:1, p:2, ml:-1}}>
                            Job Overview
                        </Typography>
                    </Grid>

                    <Grid item>
                            <Typography sx={{ml:1, mr:1}} align="justify">
                                {desc}
                            </Typography>
                    </Grid>
                    
                </Paper>
            </Box>

    );
}

const FormItems = [
    {
        first: 'First Name',
        second: 'Middle Name',
        third: 'Last Name'
    },
    {
        first: 'Birth Date',
        second: 'Phone Number',
        third: 'Email'
    }
]

const FormInput = () => {
    return (

        <Grid item
                    md={12}
                    xs={12}
                    sm={12}>

                    {
                    FormItems.map((item, i) => (
                        
                        <Grid item container
                            sx={
                                {mt: 2}
                            }
                            md={12}>
                            <Grid item
                                md={4}>
                                <TextField sx={
                                        {
                                            width: 240,
                                            marginLeft: 3
                                        }
                                    }
                                    required
                                    id={
                                        item.first
                                    }
                                    label={
                                        item.first
                                    }
                                    defaultValue={
                                        item.first
                                    }/>
                            </Grid>
                            <Grid item
                                md={4}>
                                <TextField sx={
                                        {width: 240}
                                    }
                                    required
                                    id={
                                        item.second
                                    }
                                    label={
                                        item.second
                                    }
                                    defaultValue={
                                        item.second
                                    }/>
                            </Grid>
                            <Grid item
                                md={4}>
                                <TextField sx={
                                        {width: 240, marginLeft:-3}
                                    }
                                    required
                                    id={
                                        item.third
                                    }
                                    label={
                                        item.third
                                    }
                                    defaultValue={
                                        item.third
                                    }/>
                            </Grid>
                        </Grid>
                    ))
                } </Grid>
    );
}

const CardTemplate = (props) => {
    return (
        <Card style={{}} sx={
            {
                ml: 3, mt:1,
                border: 1,
                borderStyle:"dashed",
                width: 200,
                height: 70,
                color:"brown",
                borderColor:"black",
                borderRadius: 2
            }
        }>
            <CardContent sx={{p:1}}>
                <Grid container  >
                    
                    <Grid item xs={10} sm={10} md={10} sx={{mt:1}}>
                        <Grid container>
                            <Grid item xs={12} sm={12} md={12}>
                                <Typography 
                                    fontSize={15}
                                    color={"black"}
                                    sx={{mx:2.5}}
                                    align={"left"}>
                                    
                                    {props.title} 
                                </Typography>
                            </Grid>
                            <Grid item xs={12} sm={12} md={12}>
                                <Typography sx={
                                        {
                                            fontSize: 12,
                                            color: "black",
                                            mx:2.5
                                        }
                                    }
                                    align={"left"}>
                                    {props.content} 
                                </Typography>
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid item xs={2} sm={2} md={2} sx={{mt:2}} >
                        {props.logo}
                    </Grid>
                </Grid>

            </CardContent>
        </Card>
    );
};

export default function ApplicationForm() {
    
    return (
    <Grid container direction="row" spacing={1} >
      <Grid item container direction="column" md={3} spacing={1} sx={{mt:2}}>
        <Grid item>
            <CompanyInfo/>
        </Grid>
        <Grid item>
            <JobInfo/>
        </Grid>
      </Grid>
      <Grid item md={9} sx={{mt:2}} spacing={1}>
            <Box  sx={{   
                        width: 1, 
                        maxWidth:840,
                        height:'88vh',
                        bgcolor: "white",
                        borderRadius: 2
                    }}>
                <Paper elevation={0}>
                    <Grid item>
                        <Typography style={{fontWeight:650, fontSize:22}} sx={{mt:1, p:3}}>
                            Fill the job applications
                        </Typography>
                    </Grid>
                    <FormInput/>
                    <Grid item>
                        <Typography style={{fontWeight:650, fontSize:18}} sx={{mt:1, p:3}}>
                            About You
                        </Typography>
                    </Grid>
                    <Grid item>
                            <Typography sx={{ml:3, mr:3}} align="justify">
                                {aboutYou}
                            </Typography>
                    </Grid>
                    
                    <Divider sx={{m:3}}/>
                    
                    <Grid item>
                        <Typography style={{fontWeight:650, fontSize:18}} sx={{ml:3}}>
                            Attach Your Resume
                        </Typography>
                    </Grid>

                    <Grid item container>
                        <Grid item>
                            <CardTemplate logo={<Upload/>} title="Upload Resume" content="(Format: .Pdf, .Doc)"/>
                        </Grid>
                        <Grid item>
                            <CardTemplate logo={<Article/>} title="Resume.pdf" content="871 KB"/>
                        </Grid>
                    </Grid>

                    <Grid item container sx={{ml:1, mt:2}} spacing={2}>
                    <Grid item>
                        <Button variant="contained" sx={{borderRadius:4, width:150}}>
                            Submit
                        </Button>
                    </Grid>

                    <Grid item>
                        <Button variant="contained" sx={{borderRadius:4, width:150}} disabled>
                            Cancel
                        </Button>
                    </Grid>
                    </Grid>
                    
                </Paper>
            </Box>
        </Grid>
    </Grid>
    );
}
